set -g default-terminal alacritty
set -g mouse on
set -g set-titles on
set -g set-titles-string "#S"

# https://github.com/tmux-plugins/tmux-resurrect#installation-with-tmux-plugin-manager-recommended
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
